# Generated by Django 4.2.7 on 2023-12-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_customer_alter_project_engineers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='project_title',
        ),
    ]
