# Generated by Django 4.2.7 on 2023-12-07 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_engineer_teamleader_delete_team_engineer_team_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'customer_projects__isnull': True, 'is_customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_manager': True, 'managed_projects__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
