# Generated by Django 4.2.7 on 2023-12-05 11:52

from django.db import migrations, models
import django.utils.timezone
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.IntegerField(default=ticket.models.random_ticket_id, unique=True),
        ),
    ]
