# Generated by Django 4.2.7 on 2023-12-07 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0004_ticket_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_assigned_to_leader',
        ),
        migrations.AddField(
            model_name='ticket',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
