# Generated by Django 4.2.7 on 2023-12-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_remove_ticket_is_assigned_to_leader_ticket_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
